# Generated by Django 4.2.5 on 2023-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_busday'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='adress',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
