# Generated by Django 4.2.5 on 2023-11-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_teacher_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='adress',
            new_name='address',
        ),
    ]
