# Generated by Django 4.2.5 on 2023-11-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.IntegerField(),
        ),
    ]
