# Generated by Django 4.2.5 on 2023-11-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_status_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
