# Generated by Django 4.2.5 on 2023-11-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
